# 生产环境配置文件
# @author <a href="https://github.com/ouyangtn">github</a>
# @from <a href="https://github.com/ouyangtn">程序员红豆</a>
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/hongdouoj
    username: xxxx
    password: xxxxxxxx
  # Redis 配置
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
  rabbitmq:
    host: rabbitmq
    port: 5672
    password: xxxxx
    username: xxxxx
