# 生产环境配置文件
# @author <a href="https://github.com/ouyangtn">github</a>
# @from <a href="https://github.com/ouyangtn">程序员红豆</a>
spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
    gateway:
      routes:
        - id: hongdouoj-backend-user-service
          uri: lb://hongdouoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: hongdouoj-backend-question-service
          uri: lb://hongdouoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: hongdouoj-backend-judge-service
          uri: lb://hongdouoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: hongdouoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8101
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2